### ISSUE TITLE
D10.2.3

### ISSUE THREAD

**Issue by limelect** [tinyBigGAMES/Luna#4]
compiling demos
errors
first error
   class operator Initialize(out aDest: TLuPoint);

Checking project dependencies...
Compiling BasicTemplate.dproj (Debug, Win64)
brcc32 command line for "BasicTemplate.vrc"
  c:\program files (x86)\embarcadero\studio\19.0\bin\cgrc.exe -c65001 "BasicTemplate.vrc" -foBasicTemplate.res 
dcc64 command line for "BasicTemplate.dpr"
  c:\program files (x86)\embarcadero\studio\19.0\bin\dcc64.exe -$O- -$W+ -$R+ -$Q+ --no-config -M -Q -TX.exe 
  -AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;
  DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DDEBUG -E..\..\..\bin -I"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\debug";"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win64\release";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files 
  (x86)\embarcadero\studio\19.0\include";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program 
  Files (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -LEC:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64 
  -LNC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64 -NU.\Win64\Debug -NSWinapi;System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;
  System;Xml;Data;Datasnap;Web;Soap;Vcl;Vcl.Imaging;Vcl.Touch;Vcl.Samples;Vcl.Shell; -O"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win64\release";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files 
  (x86)\embarcadero\studio\19.0\include";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program 
  Files (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -R"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -U"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\debug";"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win64\release";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files 
  (x86)\embarcadero\studio\19.0\include";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program 
  Files (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -CC -V -VN -VR -NBC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64 
  -NHC:\Users\Public\Documents\Embarcadero\Studio\19.0\hpp\Win64 -NO.\Win64\Debug   BasicTemplate.dpr   
[dcc64 Error] Luna.pas(14683): E2393 Invalid operator declaration
[dcc64 Error] Luna.pas(14683): E2029 ',' or ')' expected but identifier 'aDest' found
[dcc64 Error] Luna.pas(14689): E2393 Invalid operator declaration
[dcc64 Error] Luna.pas(14689): E2004 Identifier redeclared: 'out'
[dcc64 Error] Luna.pas(14689): E2004 Identifier redeclared: 'TLuVector'
[dcc64 Error] Luna.pas(14693): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(14695): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(14696): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(14697): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(14698): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(14700): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(14701): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(14703): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(14706): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(14709): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(14709): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(14720): E2393 Invalid operator declaration
[dcc64 Error] Luna.pas(14720): E2004 Identifier redeclared: 'out'
[dcc64 Error] Luna.pas(14720): E2004 Identifier redeclared: 'TLuRect'
[dcc64 Error] Luna.pas(14723): E2005 'TLuRect' is not a type identifier
[dcc64 Error] Luna.pas(14676): E2005 'TLuPoint' is not a type identifier
[dcc64 Error] Luna.pas(14686): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(14713): E2005 'TLuRect' is not a type identifier
[dcc64 Error] Luna.pas(15207): E2029 '..' expected but ';' found
[dcc64 Error] Luna.pas(15208): E2029 '..' expected but ';' found
[dcc64 Error] Luna.pas(15255): E2029 '..' expected but ';' found
[dcc64 Error] Luna.pas(15290): E2029 '..' expected but ';' found
[dcc64 Error] Luna.pas(15291): E2029 '..' expected but ';' found
[dcc64 Error] Luna.pas(15292): E2029 '..' expected but ';' found
[dcc64 Error] Luna.pas(15309): E2005 'TLuRect' is not a type identifier
[dcc64 Error] Luna.pas(15312): E2005 'TLuRect' is not a type identifier
[dcc64 Error] Luna.pas(15313): E2005 'TLuRect' is not a type identifier
[dcc64 Error] Luna.pas(15459): E2029 '..' expected but ';' found
[dcc64 Error] Luna.pas(15581): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(15581): E2005 'TLuRect' is not a type identifier
[dcc64 Error] Luna.pas(15582): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(15583): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(15584): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(15584): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(15585): E2005 'TLuVector' is not a type identifier
[dcc64 Error] Luna.pas(15585): E2005 'TLuRect' is not a type identifier
[dcc64 Error] Luna.pas(15586): E2005 'TLuRect' is not a type identifier
[dcc64 Error] Luna.pas(15587): E2005 'TLuRect' is not a type identifier
[dcc64 Error] Luna.pas(15621): E2005 'TLuRect' is not a type identifier
[dcc64 Error] Luna.pas(15624): E2005 'TLuRect' is not a type identifier
[dcc64 Error] Luna.pas(15625): E2005 'TLuRect' is not a type identifier
[dcc64 Error] Luna.pas(21874): E2037 Declaration of 'TLuPoint' differs from previous declaration
[dcc64 Error] Luna.pas(21876): E2066 Missing operator or semicolon
[dcc64 Error] Luna.pas(21876): E2003 Undeclared identifier: 'aValue'
[dcc64 Error] Luna.pas(21880): E2037 Declaration of 'TLuPoint' differs from previous declaration
[dcc64 Error] Luna.pas(21882): E2066 Missing operator or semicolon
[dcc64 Error] Luna.pas(21882): E2066 Missing operator or semicolon
[dcc64 Error] Luna.pas(21883): E2066 Missing operator or semicolon
[dcc64 Error] Luna.pas(21883): E2066 Missing operator or semicolon
[dcc64 Error] Luna.pas(21886): E2037 Declaration of 'TLuPoint' differs from previous declaration
[dcc64 Fatal Error] Luna.pas(21888): E2226 Compilation terminated; too many errors
Failed
Elapsed time: 00:00:00.4

**Comment by jarroddavis68** [comment]
Add support for Delphi 10.2.x. Thanks for reporting.

https://user-images.githubusercontent.com/69952438/194388153-19322fa8-78cf-4a31-abf3-08d283be0a9e.mp4

**Comment by limelect** [comment]
Now it compiles BUT
![Screenshot - 07_10_2022 , 09_43_52](https://user-images.githubusercontent.com/4199131/194484964-fc8d045d-f85d-4196-b945-010d4616932f.jpg)

**Comment by jarroddavis68** [comment]
Do they run and exit with the memory leak or when run, just terminates immediately with the leak?

I see you are using Windows 7, just to be clear, it's has not been tested at all on older OSes. SDL was built using VS 2022 linked aginst the Windows 10 SDK.I statically linked the vcruntime however, thereby minimizing run-time dependencies, thus making it much easier to run on older OSes. There still maybe the issue of making a system call that does not exist. I do not have Windows 7 setup currently, so I am unable to check this myself. There seems to be one `TResourceStream` that is leaking which means a crash sometime after it was open. My first place to look would be `procedure LoadDLL`. If you could please step through this routine and see if there are any issues. The other would be `function  TLuFont.LoadDefault`. Put a break point at the start of these two routines and do a debug run please. Thanks.

**Comment by limelect** [comment]
It runs and stops immediately on the above screen

**Comment by limelect** [comment]
OK i debugged up to
It process   TProc(P)();

On system.PAS (Delphi D10.2.3 !!!! RTL) on line 22610 procedure InitUnits;
Count =198
Too much for me to spend time

    while I < Count do
    begin
      P := Table^[I].Init;
      Inc(I);
      InitContext.InitCount := I;
      if Assigned(P) and Assigned(Pointer(P^)) then
      begin
{$IF defined(MSWINDOWS)}
        TProc(P)();
{$ELSEIF (defined(POSIX) and defined(CPUX86)) and defined(ASSEMBLER)}
        CallProc(P, InitContext.Module^.GOT);
{$ELSE}
        TProc(P)();
{$ENDIF}
      end;
    end;
  except
    FinalizeUnits;
    raise;
  end;
